trigger:
  - main

pool:
  name: Default

jobs:
- job: ToscaCIExecution
  steps:
  - task: CmdLine@2
    inputs:
      script: '"C:\agents\vsts-agent-win-x64-4.255.0\Client\TOSCACIClient.exe" -m distributed -s "http://localhost" -p "SampleDex" -events ''["Dex Demo"]'' -r "C:\agents\result"'
