pool:
  name: Default

steps:
  - powershell: |
      # run the .ps1 via a child PowerShell process with ExecutionPolicy Bypass
      powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\Users\praun\Downloads\tosca_execution_client.ps1" `
        -toscaServerUrl "http://127.0.0.1:81/" `
        -events '["Test"]' `
        -projectName "TestCI" `
        -clientId "$(ToscaClientId)" `
        -clientSecret "$(ToscaClientSecret)"
    displayName: 'Run Tosca execution client (Bypass EP)'
