trigger:
  - main

pool:
  name: Default

jobs:
- job: ToscaCIExecution
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: '"C:\agents\vsts-agent-win-x64-4.255.0\Client\TOSCACIClient.exe" -m local|distributed -s "http://localhost" -p "SampleDex" -events ''["Dex Demo"]'' -r "C:\agents\result"'
