trigger:
  - main

pool:
  name: Default

jobs:
- job: ToscaCIExecution
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        & "C:\agents\vsts-agent-win-x64-4.255.0\Client\TOSCACIClient.exe" `
          -toscaServerUrl "http://localhost" `
          -projectName "SampleDex" `
          -events '["Dex Demo"]'
