- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      & "C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\ToscaCI\ToscaCIClient.exe" ^
      /RunExecution ^
      /WorkspacePath:"C:\Tosca\Workspace\Default.tws" ^
      /ExecutionList:"MyExecutionList" ^
      /ResultDir:"C:\Tosca\Results"
