trigger:
  - main  # ✅ list under a mapping key (trigger)

pool:
  name: Default  # ✅ mapping (key: value)

jobs:
- job: ToscaCIExecution  # ✅ list inside a mapping key (jobs)
  steps:
    - task: CmdLine@2
      inputs:
        script: |
          "C:\agents\vsts-agent-win-x64-4.255.0\Client\TOSCACIClient.exe" ^
            -m Distributed ^
            -s "http://localhost:80" ^
            -p "SampleDex" ^
            -t "Dex Demo" ^
            -r "C:\ToscaResults"
