trigger:
  - main  # Or your actual branch name

pool:
  name: Default  # Use your self-hosted agent pool name

jobs:
- job: ToscaCIExecution
  steps:
    - task: CmdLine@2
      inputs:
        script: |
          "C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\ToscaCI\ToscaCIClient.exe" ^
            /ServerUrl=http://localhost:8731 ^
            /ProjectName="SampleDex" ^
            /Events="Dex Demo" ^
            /ResultsPath="C:\ToscaResults" ^
            /ExecutionMode=Run
