trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'SampleDex'
  environment: 'Dex'
  eventId: 'Dex Demo'
  testSetName: 'JSON Example'

steps:
- task: PowerShell@2
  name: CallToscaExecutionAPI
  inputs:
    targetType: 'inline'
    script: |
      $authUrl = "http://127.0.0.1:81/tua/connect/token"
      $clientId = "M9VqjcVcrEuoAgv90714eQ"
      $clientSecret = "Djdvho9h_EeihnFrFyzCDweKadNGM5FUeiv07kZVw6CA"

      $body = @{
          grant_type    = "client_credentials"
          client_id     = $clientId
          client_secret = $clientSecret
      }

      $response = Invoke-RestMethod -Uri $authUrl -Method Post -Body $body -ContentType "application/x-www-form-urlencoded"

      if (-not $response.access_token) {
        Write-Error "Failed to retrieve access token"
        exit 1
      }

      $token = $response.access_token
      Write-Host "Access token retrieved successfully"
