trigger:
  - main

pool:
  vmImage: 'windows-latest'

jobs:
  - job: RunToscaTasks
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $scriptPath = "C:\temp\tosca_execution_client.ps1"

            if (Test-Path $scriptPath) {
              Write-Host "Script found at $scriptPath. Executing..."
              & $scriptPath `
                -toscaServerUrl http://localhost.com `
                -projectName "SampleDex" `
                -events '["Dex Demo"]' `
                -resultsFolderPath "C:\"
            } else {
              throw "Script not found at $scriptPath. Failing pipeline."
            }
