steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.19.2'
    # You can also change 'lts' to any supported LTS Node.js version.
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim \
    --token "U1G8cYjHuLDt3sfyTfqRtkf6bhq8MVksQJ4Lckak5MIt5fg1rP" \
    --project "t8lmkDvNwtSpcDCQscmU" \
    --grid "Testim-Grid-before" \
    --branch "master" \
    --label "test" \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  displayName: 'publish testim test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml'